/*
    MakeMKV GUI - Graphics user interface application for MakeMKV

    Copyright (C) 2007-2015 GuinpinSoft inc <makemkvgui@makemkv.com>

    You may use this file in accordance with the end user license
    agreement provided with the Software. For licensing terms and
    conditions see License.txt

    This Software is distributed on an "AS IS" basis, WITHOUT WARRANTY
    OF ANY KIND, either express or implied. See the License.txt for
    the specific language governing rights and limitations.

*/


#define AP_IMG_ABOUT 0
#define AP_IMG_ABOUT_COUNT 6
#define AP_IMG_BACKUP 6
#define AP_IMG_BACKUP_COUNT 6
#define AP_IMG_CLEARLOG 12
#define AP_IMG_CLEARLOG_COUNT 6
#define AP_IMG_CONFIGURE 18
#define AP_IMG_CONFIGURE_COUNT 6
#define AP_IMG_SAVE 24
#define AP_IMG_SAVE_COUNT 6
#define AP_IMG_EJECT 30
#define AP_IMG_EJECT_COUNT 6
#define AP_IMG_OPENDISC 36
#define AP_IMG_OPENDISC_COUNT 6
#define AP_IMG_OPENFILE 42
#define AP_IMG_OPENFILE_COUNT 6
#define AP_IMG_OPENFILE2 48
#define AP_IMG_OPENFILE2_COUNT 6
#define AP_IMG_OPENFOLDER 54
#define AP_IMG_OPENFOLDER_COUNT 6
#define AP_IMG_OPENFOLDER2 60
#define AP_IMG_OPENFOLDER2_COUNT 6
#define AP_IMG_REVERT 66
#define AP_IMG_REVERT_COUNT 4
#define AP_IMG_STREAM 70
#define AP_IMG_STREAM_COUNT 6
#define AP_IMG_STOP 76
#define AP_IMG_STOP_COUNT 6
#define AP_IMG_PREVIEW 82
#define AP_IMG_PREVIEW_COUNT 6
#define AP_IMG_MKVICON 88
#define AP_IMG_MKVICON_COUNT 6
#define AP_IMG_ANIMATION0102 94
#define AP_IMG_ANIMATION0102_COUNT 2
#define AP_IMG_ANIMATION0205 96
#define AP_IMG_ANIMATION0205_COUNT 50
#define AP_IMG_ANIMATION0505 146
#define AP_IMG_ANIMATION0505_COUNT 8
#define AP_IMG_ANIMATION0506 154
#define AP_IMG_ANIMATION0506_COUNT 8
#define AP_IMG_ANIMATION0606 162
#define AP_IMG_ANIMATION0606_COUNT 8
#define AP_IMG_ANIMATION0621 170
#define AP_IMG_ANIMATION0621_COUNT 1
#define AP_IMG_ANIMATION0622 171
#define AP_IMG_ANIMATION0622_COUNT 1
#define AP_IMG_ANIMATION0623 172
#define AP_IMG_ANIMATION0623_COUNT 1
#define AP_IMG_ANIMATION0102H 173
#define AP_IMG_ANIMATION0102H_COUNT 2
#define AP_IMG_ANIMATION0205H 175
#define AP_IMG_ANIMATION0205H_COUNT 50
#define AP_IMG_ANIMATION0505H 225
#define AP_IMG_ANIMATION0505H_COUNT 8
#define AP_IMG_ANIMATION0506H 233
#define AP_IMG_ANIMATION0506H_COUNT 8
#define AP_IMG_ANIMATION0606H 241
#define AP_IMG_ANIMATION0606H_COUNT 8
#define AP_IMG_ANIMATION0621H 249
#define AP_IMG_ANIMATION0621H_COUNT 1
#define AP_IMG_ANIMATION0622H 250
#define AP_IMG_ANIMATION0622H_COUNT 1
#define AP_IMG_ANIMATION0623H 251
#define AP_IMG_ANIMATION0623H_COUNT 1


